version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"  # hôte:conteneur
    networks:
      - app-network

  web:
    build: .
    container_name: django_web
    restart: always
    command: gunicorn delais_paiements.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app  # Retirer en prod pour image immuable
      - static_volume:/app/staticfiles
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      RUNNING_IN_DOCKER: '1'
    networks:
      - app-network

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - app-network

volumes:
  mysql_data:
  static_volume:

networks:
  app-network:
    driver: bridge
