version: '3.8'

services:
  db:
    image: mysql:8.0-debian
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Masteribk2019++"
      MYSQL_DATABASE: "delais"
      MYSQL_USER: "IBK"
      MYSQL_PASSWORD: "Masteribk2019++"
    command: --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD", "-e", "SELECT 1;"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  web:
    build: .
    container_name: django_web
    restart: always
    command: >
      bash -c "./wait-for-db.sh db 3306 &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn delais_paiements.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app  # Retirer en prod pour image immuable
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      RUNNING_IN_DOCKER: '1'
    networks:
      - app-network

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - app-network

volumes:
  mysql_data:
  static_volume:

networks:
  app-network:
    driver: bridge
