services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-delais}
      MYSQL_USER: ${DB_USER:-IBK}
      MYSQL_PASSWORD: ${DB_PASS:-Masteribk2019++}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      RUNNING_IN_DOCKER: "1"
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-delais}
      DB_USER: ${DB_USER:-IBK}
      DB_PASS: ${DB_PASS:-Masteribk2019++}
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,10.211.0.249}
      SECRET_KEY: ${SECRET_KEY:-change-me}
    ports:
      - "8000:8000"
    volumes:
      - static-data:/app/staticfiles
    command: ["gunicorn", "delais_paiements.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "8080:80"
    volumes:
      - static-data:/app/staticfiles:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db-data:
  static-data: