# Generated by Django 4.2.23 on 2025-08-03 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=255, unique=True, verbose_name='Raison Sociale')),
                ('numero_if', models.CharField(max_length=20, unique=True, verbose_name="N° d'Identifiant Fiscal (IF)")),
                ('numero_ice', models.CharField(blank=True, max_length=30, null=True, verbose_name="N° d'Identifiant Commun de l'Entreprise (ICE)")),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.IntegerField(choices=[(1, 'Trimestre 1'), (2, 'Trimestre 2'), (3, 'Trimestre 3'), (4, 'Trimestre 4')], verbose_name='Période')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('chiffre_affaires_n1', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Chiffre d'affaires N-1")),
                ('statut', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis')], default='DRAFT', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='core.client', verbose_name='Client')),
                ('collaborateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateur')),
            ],
            options={
                'verbose_name': 'Déclaration',
                'verbose_name_plural': 'Déclarations',
                'ordering': ['-annee', '-periode'],
                'unique_together': {('client', 'periode', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur_if', models.CharField(max_length=20, verbose_name='N° IF Fournisseur')),
                ('fournisseur_ice', models.CharField(blank=True, max_length=30, null=True, verbose_name='N° ICE Fournisseur')),
                ('fournisseur_raison_sociale', models.CharField(max_length=255, verbose_name='Raison Sociale Fournisseur')),
                ('numero_facture', models.CharField(max_length=100, verbose_name='N° de facture')),
                ('date_emission_facture', models.DateField(verbose_name="Date d'émission")),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant TTC')),
                ('montant_paye_hors_delai', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant payé hors délai')),
                ('date_paiement_hors_delai', models.DateField(blank=True, null=True, verbose_name='Date paiement hors délai')),
                ('montant_non_paye', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant non encore payé')),
                ('montant_objet_litige', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant en litige')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.declaration')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
    ]
