# Generated by Django 4.2.23 on 2025-08-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='annee_transaction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année (transaction périodique)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_constatation_service',
            field=models.DateField(blank=True, null=True, verbose_name='Date constatation service (public)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_jugement_definitif',
            field=models.DateField(blank=True, null=True, verbose_name='Date du jugement définitif'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_livraison',
            field=models.DateField(blank=True, null=True, verbose_name='Date de livraison/prestation'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_paiement_convenue',
            field=models.DateField(blank=True, null=True, verbose_name='Date convenue pour le paiement'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_paiement_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue pour le paiement'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_paiement_prevue_secteur',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue paiement (secteur)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_recours_judiciaire',
            field=models.DateField(blank=True, null=True, verbose_name='Date du recours judiciaire'),
        ),
        migrations.AddField(
            model_name='facture',
            name='delai_paiement_secteur',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Délai de paiement secteur'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fournisseur_adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse siège social'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fournisseur_rc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° RC'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fournisseur_ville_rc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville du RC'),
        ),
        migrations.AddField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='facture',
            name='mois_retard_non_paye',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de mois de retard (non payé)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='mois_retard_paye',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de mois de retard (payé)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='mois_suspension_amende',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre mois suspension amende'),
        ),
        migrations.AddField(
            model_name='facture',
            name='mois_transaction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mois (transaction périodique)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_du_apres_jugement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant dû après jugement'),
        ),
        migrations.AddField(
            model_name='facture',
            name='nature_prestation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nature des marchandises, travaux ou services'),
        ),
        migrations.AddField(
            model_name='facture',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Références du paiement'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_emission_facture',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'émission"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_paiement_hors_delai',
            field=models.DateField(blank=True, null=True, verbose_name='Date du paiement hors délai'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='fournisseur_ice',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="N° d'ICE"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='fournisseur_if',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="N° d'IF"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='fournisseur_raison_sociale',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom et prénom ou raison sociale'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_objet_litige',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant objet de litiges'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant de la facture TTC'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de facture'),
        ),
    ]
