# Generated by Django 4.2.23 on 2025-08-06 08:37

from django.db import migrations, models, connection
import django.utils.timezone


def drop_facture_retard_cols():
    """Supprime les colonnes retard si elles existent (idempotent)."""
    with connection.cursor() as cur:
        for col in ('mois_retard_non_paye', 'mois_retard_paye'):
            cur.execute("SHOW COLUMNS FROM `core_facture` LIKE %s", [col])
            if cur.fetchone():
                cur.execute(f"ALTER TABLE `core_facture` DROP COLUMN `{col}`")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_facture_annee_transaction_and_more'),
    ]

    operations = [
        migrations.RunPython(lambda apps, schema_editor: drop_facture_retard_cols(), lambda apps, schema_editor: None),
        migrations.AlterField(
            model_name='facture',
            name='date_jugement_definitif',
            field=models.DateField(blank=True, null=True, verbose_name='Date Jugement Définitif'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_recours_judiciaire',
            field=models.DateField(blank=True, null=True, verbose_name='Date Recours Judiciaire'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='mois_suspension_amende',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre mois de suspension pénalités'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_du_apres_jugement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant Dû (Jugement)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_objet_litige',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant en Litige'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=15, verbose_name='Montant de la facture TTC'),
            preserve_default=False,
        ),
    ]
