# Generated by Django 4.2.23 on 2025-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_facture_mois_retard_non_paye_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('1', 'Espèces'), ('2', 'Chèque'), ('3', 'Prélèvement'), ('4', 'Virement'), ('5', 'Effets')], max_length=2, null=True, verbose_name='Mode de paiement'),
        ),
    ]
