# Generated by Django 4.2.23 on 2025-08-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_facture_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mode de paiement'),
        ),
    ]
