# Generated by Django 4.2.23 on 2025-08-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_facture_nombre_mois_retard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='nombre_mois_retard',
        ),
    ]
