# Generated by Django 4.2.23 on 2025-08-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_facture_nombre_mois_retard'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='nombre_mois_retard',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre mois de retard'),
        ),
    ]
