# Generated by Django 4.2.23 on 2025-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facture_nombre_mois_retard'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='amende',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Amende'),
        ),
    ]
