# Generated by Django 4.2.23 on 2025-08-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_facture_amende'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='taux_directeur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux Directeur (%)'),
        ),
    ]
