# Generated by Django 4.2.23 on 2025-08-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_declaration_taux_directeur'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='declaration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='declaration',
            name='type_declaration',
            field=models.CharField(choices=[('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], default='TRIMESTRIEL', max_length=12, verbose_name='Type de Déclaration'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='periode',
            field=models.IntegerField(blank=True, choices=[(1, 'Trimestre 1'), (2, 'Trimestre 2'), (3, 'Trimestre 3'), (4, 'Trimestre 4')], null=True, verbose_name='Période'),
        ),
        migrations.AlterUniqueTogether(
            name='declaration',
            unique_together={('client', 'type_declaration', 'periode', 'annee')},
        ),
    ]
