# Generated by Django 4.2.23 on 2025-08-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_declaration_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(verbose_name='Mois')),
                ('numero_facture', models.CharField(max_length=100, verbose_name='N° Facture')),
                ('date_facture', models.DateField(verbose_name='Date Facture')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation des biens et services')),
                ('nom_fournisseur', models.CharField(max_length=255, verbose_name='Nom Fournisseur')),
                ('if_fournisseur', models.CharField(max_length=20, verbose_name='IF Fournisseur')),
                ('ice_fournisseur', models.CharField(max_length=30, verbose_name='ICE Fournisseur')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant HT')),
                ('code_tva', models.CharField(choices=[('20', '20%'), ('14', '14%'), ('10', '10%'), ('7', '7%'), ('0', 'Exonéré')], max_length=3, verbose_name='Code TVA')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant TTC')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement'), ('EFFET', 'Effet'), ('COMPENSATION', 'Compensation'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Mode Paiement')),
                ('date_paiement', models.DateField(verbose_name='Date Paiement')),
                ('prorata', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Prorata (%)')),
                ('nombre_mois', models.IntegerField(blank=True, null=True, verbose_name='Nombre de mois')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_factures', to='core.declaration')),
            ],
            options={
                'verbose_name': 'Relevé de Facture',
                'verbose_name_plural': 'Relevés de Factures',
                'ordering': ['mois', 'date_facture'],
            },
        ),
    ]
