# Generated by Django 4.2.23 on 2025-08-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_relevefacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('1', 'Espèces'), ('2', 'Chèque'), ('3', 'Prélèvement'), ('4', 'Virement'), ('5', 'Effets'), ('6', 'Compensation'), ('7', 'Autres')], max_length=2, null=True, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='relevefacture',
            name='code_tva',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code TVA'),
        ),
        migrations.AlterField(
            model_name='relevefacture',
            name='mode_paiement',
            field=models.CharField(choices=[('1', 'Espèces'), ('2', 'Chèque'), ('3', 'Prélèvement'), ('4', 'Virement'), ('5', 'Effet'), ('6', 'Compensation'), ('7', 'Autre')], max_length=20, verbose_name='Mode Paiement'),
        ),
    ]
