# Generated by Django 4.2.23 on 2025-08-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_facture_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevefacture',
            name='amende',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Amende'),
        ),
    ]
