# Generated by Django 4.2.23 on 2025-08-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_relevefacture_amende'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevefacture',
            name='amende',
        ),
    ]
