# Generated by Django 4.2.23 on 2025-08-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_relevefacture_amende'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevefacture',
            name='nombre_mois',
        ),
        migrations.AddField(
            model_name='relevefacture',
            name='nombre_jours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de jours'),
        ),
    ]
