# Generated by Django 4.2.23 on 2025-08-23 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_remove_relevefacture_nombre_mois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='collaborateurs',
            field=models.ManyToManyField(blank=True, related_name='clients_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateurs assignés'),
        ),
    ]
