# Generated by Django 4.2.23 on 2025-08-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Notes internes sur la validation ou le rejet de l'inscription", verbose_name='Notes administratives'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name="Statut de l'inscription"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation/rejet'),
        ),
    ]
